name: feeder_fishing_competition
description: A real-time multiplayer fishing competition game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_database: ^10.2.5
  firebase_analytics: ^10.4.5
  cloud_functions: ^4.3.5
  firebase_storage: ^11.2.6
  
  # State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.7
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  lottie: ^2.6.0
  
  # Utilities
  intl: ^0.18.1
  equatable: ^2.0.5
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  collection: ^1.17.1
  logger: ^1.4.0
  
  # Animation
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/
    
  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/game_font_regular.ttf
        - asset: assets/fonts/game_font_bold.ttf
          weight: 700